name: ECMWF FFPI Kuwait

on:
  workflow_dispatch:
  schedule:
    - cron: "30 1,7,13,19 * * *"

permissions:
  contents: write

jobs:
  update-map:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install numpy pandas xarray cfgrib eccodes matplotlib cartopy scipy requests ecmwf-opendata

      - name: Run ECMWF FFPI
        run: python ecmwf_ffpi.py

      - name: Save updated map
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git diff --cached --quiet || git commit -m "Update ECMWF FFPI map"
          git push
